server:
  port: 8888
 
spring:
  application:
    name: server-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#unwork
#        git:
#          uri: https://github.com/qq372777648/testgit
#          searchPaths: testgit
#          username: qq372777648
#          password: xxx
    
eureka:
  instance:
    non-secure-port: ${server.port:8888}
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/