eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: consume-hello-ribbon-and-feign
    
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consume-hello-ribbon-and-feign
    api-b:
      path: /api-b/**
      serviceId: service-hi

    